import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';
import 'package:transfusio/src/core/utils/constants/app_dimensions.dart';
import 'package:transfusio/src/shared/presentation/widgets/app_bars/simple_app_bar.dart';

class LegalContentScreen extends StatefulWidget {
  final int type;
  const LegalContentScreen({required this.type, super.key});
  @override
  LegalContentScreenState createState() => LegalContentScreenState();
}

class LegalContentScreenState extends State<LegalContentScreen> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: SimpleAppBar(
        title:
            widget.type == 1
                ? "Termes et conditions"
                : "Politique de confidentialité",
      ),
      body: ListView(
        padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 5),
        children: [
          SizedBox(
            width: Dimensions.getScreenWidth(context),
            child:
                widget.type == 1
                    ? const HtmlWidget(
                      """<h1><strong>CONDITIONS D'UTILISATION DE transfusio</strong></h1>
<p><span style="font-weight: 400;">Date d'entr&eacute;e en vigueur : 29 d&eacute;cembre 2023</span></p>
<p><span style="font-weight: 400;">Si vous r&eacute;sidez en Afrique, vous acceptez les pr&eacute;sentes conditions d'utilisation avec transfusio.&nbsp;</span></p>
<p><span style="font-weight: 400;">transfusio et ses partenaires (&laquo; </span><strong>transfusio </strong><span style="font-weight: 400;">&raquo; ou &laquo; </span><strong>nous</strong><span style="font-weight: 400;"> &raquo;) propose aux utilisateurs (&laquo; </span><strong>Utilisateurs</strong><span style="font-weight: 400;"> &raquo; ou &laquo; </span><strong>Vous</strong><span style="font-weight: 400;"> &raquo;) des services de participation citoyenne au d&eacute;veloppement n&eacute;goci&eacute;s via diverses applications logicielles et services, y compris, mais sans s'y limiter, l'application &laquo; MiGbloin Antiarnaque&raquo;. Ces conditions d'utilisation et la&nbsp; </span><a href="https://www.truecaller.com/privacy-policy"><span style="font-weight: 400;">politique de confidentialit&eacute;</span></a><span style="font-weight: 400;"> de transfusio (les &laquo; </span><strong>Conditions</strong><span style="font-weight: 400;"> &raquo;) r&eacute;giront votre utilisation des applications logicielles, des sites Web, de l'API des services Web, des outils ou d'autres services et fonctionnalit&eacute;s fournis par transfusio de temps &agrave; autre (collectivement &laquo; Services &raquo;). En acc&eacute;dant ou en utilisant l'un des services, vous acceptez d'&ecirc;tre li&eacute; par les pr&eacute;sentes conditions. En utilisant l'application MiGbloin Antiarnaque, Vous confirmez que vous &ecirc;tes r&eacute;sident du pays d&rsquo;Afrique auquel appartient l'indicatif international du num&eacute;ro de t&eacute;l&eacute;phone que vous avez enregistr&eacute; pour acc&eacute;der &agrave; nos Services. Lorsque d'autres services tiers sont mis &agrave; disposition dans le cadre de nos Services, les conditions de service et la politique de confidentialit&eacute; des tiers respectifs s'appliqueront &agrave; toute utilisation de votre part. Si vous vous inscrivez aupr&egrave;s de transfusio en tant qu'entit&eacute; commerciale, vous d&eacute;clarez que vous avez le pouvoir de lier l&eacute;galement cette entit&eacute;.</span></p>
<p><span style="font-weight: 400;">Certaines fonctionnalit&eacute;s des Services peuvent &ecirc;tre soumises &agrave; des directives, conditions ou r&egrave;gles suppl&eacute;mentaires, qui seront publi&eacute;es dans ou sur les Services en relation avec ces fonctionnalit&eacute;s. Toutes ces conditions , directives et r&egrave;gles suppl&eacute;mentaires sont incorpor&eacute;es par r&eacute;f&eacute;rence dans les pr&eacute;sentes Conditions.</span></p>
<h2><strong>1. INFORMATIONS PERSONNELLES</strong></h2>
<p><span style="font-weight: 400;">Nous sommes fermement engag&eacute;s &agrave; assurer la s&eacute;curit&eacute; et la protection des informations personnelles de nos utilisateurs et des services. La&nbsp; politique de confidentialit&eacute; de MiGbloin Antiarnaque d&eacute;crit la mani&egrave;re dont nous collectons, utilisons, partageons et traitons les informations personnelles et vous reconnaissez et acceptez que transfusio puisse collecter, utiliser, partager et traiter les informations personnelles comme d&eacute;crit dans la pr&eacute;sente.</span></p>
<h2><strong>2. OCTROI DE DROITS</strong></h2>
<p><span style="font-weight: 400;">Sauf accord contraire &eacute;crit s&eacute;par&eacute;ment entre nous ou comme indiqu&eacute; dans l' annexe</span><a href="https://www.truecaller.com/api-license-addendum"><span style="font-weight: 400;"> de licence API</span></a><span style="font-weight: 400;">&nbsp; et sous r&eacute;serve de votre respect des pr&eacute;sentes conditions &agrave; tout moment, transfusio vous accorde un droit personnel, non exclusif, non transf&eacute;rable et limit&eacute; d'utiliser les services, pour votre usage personnel et non commercial. Vous n'&ecirc;tes pas autoris&eacute; &agrave; utiliser les services MiGbloin Antiarnaque sur un appareil que vous ne poss&eacute;dez pas ou ne contr&ocirc;lez pas. Vous ne pouvez pas copier, d&eacute;compiler, proc&eacute;der &agrave; une ing&eacute;nierie inverse, d&eacute;sassembler, tenter de d&eacute;river le code source, modifier ou cr&eacute;er des &oelig;uvres d&eacute;riv&eacute;es des applications logicielles MiGbloin, des mises &agrave; jour ou de toute partie de celles-ci (sauf dans la mesure et uniquement dans la mesure o&ugrave; toute restriction pr&eacute;c&eacute;dente est interdit par la loi applicable ou dans la mesure express&eacute;ment autoris&eacute;e par les pr&eacute;sentes Conditions ou peut &ecirc;tre autoris&eacute; par les conditions de licence r&eacute;gissant l'utilisation de tout composant open source inclus dans les applications logicielles MiGbloin).</span></p>
<p><span style="font-weight: 400;">Vous n'avez aucun droit d'utiliser le nom, les marques commerciales ou autres symboles commerciaux de Migbloin. Tous les droits qui ne vous sont pas express&eacute;ment accord&eacute;s en vertu des pr&eacute;sentes Conditions seront conserv&eacute;s par transfusio.</span></p>
<p><span style="font-weight: 400;">Si vous souhaitez utiliser une partie des services dans le cadre de votre propre application ou modifier une partie des services, cette utilisation est soumise &agrave; l'approbation &eacute;crite pr&eacute;alable de transfusio et &agrave; la conclusion d'un accord de licence distinct avec transfusio. Toute utilisation API, commerciale ou d'entreprise des services sera r&eacute;gie par l'annexe</span><a href="https://www.truecaller.com/api-license-addendum"><span style="font-weight: 400;"> de licence API</span></a><span style="font-weight: 400;">&nbsp; ou tout autre accord distinct pouvant &ecirc;tre requis par transfusio.</span></p>
<h2><strong>3. SOUTIEN</strong></h2>
<p><span style="font-weight: 400;">transfusio s'efforce de fournir un support technique, des mises &agrave; niveau et des mises &agrave; jour ad&eacute;quates et efficaces pour les services. transfusio n'est cependant soumis &agrave; aucune obligation de fournir une assistance ou une maintenance pour les services en vertu des pr&eacute;sentes Conditions et se r&eacute;serve le droit de limiter ou d'interrompre l'assistance, les mises &agrave; niveau et les mises &agrave; jour fournies de temps &agrave; autre.</span></p>
<h2><strong>4. OBLIGATIONS ET RESTRICTIONS DE L'UTILISATEUR</strong></h2>
<p><span style="font-weight: 400;">Vous garantissez que toutes les informations et autres contenus, tels que les informations de votre profil et les informations concernant les contacts contenus dans le r&eacute;pertoire t&eacute;l&eacute;phonique de votre appareil, que vous pouvez partager avec transfusio en tant qu'utilisateur des services (ensemble &laquo; </span><strong>Contenu</strong><span style="font-weight: 400;"> &raquo;), au mieux de votre connaissance, est correct, ne viole pas la loi applicable, ne corrompra pas ou ne perturbera pas les services, et que vous avez le droit de partager le contenu avec MiGbloin afin que transfusio puisse fournir les services et partager le contenu avec d'autres utilisateurs.</span></p>
<p><span style="font-weight: 400;">Sauf accord contraire &eacute;crit s&eacute;par&eacute;ment entre nous, ou tel qu'indiqu&eacute; dans l'&nbsp; annexe</span><a href="https://www.truecaller.com/api-license-addendum"><span style="font-weight: 400;"> de licence API</span></a><span style="font-weight: 400;"> , vous ne devez pas faire d'utilisation commerciale des Services ou du Contenu ni autrement transf&eacute;rer contre valeur les Services ou le Contenu. Vous acceptez de ne pas contester les droits de MiGbloin sur, ou de tenter de toute autre mani&egrave;re de faire valoir des droits sur les Services ou tout Contenu fourni par d'autres utilisateurs, &agrave; l'exception des droits explicitement accord&eacute;s en vertu des pr&eacute;sentes Conditions. Vous acceptez d'utiliser les services et le contenu uniquement dans la mesure express&eacute;ment autoris&eacute;e par les pr&eacute;sentes conditions.</span></p>
<p><span style="font-weight: 400;">Vous acceptez de ne pas utiliser les Services, le Contenu ou les informations pour tenter de contourner le fonctionnement r&eacute;gulier des Services, ou de r&eacute;duire les frais ou la contrepartie que nous pouvons tirer des Services par quelque moyen que ce soit, y compris en cr&eacute;ant plusieurs comptes, en redirigeant le trafic, en suivant d'autres activit&eacute;s frauduleuses ou des pratiques trompeuses, en cr&eacute;ant un r&eacute;f&eacute;rentiel parall&egrave;le de celles-ci, ou en cherchant &agrave; contourner les Services ou &agrave; nous concurrencer. De plus, vous ne pouvez pas contourner, &eacute;viter ou enfreindre les restrictions g&eacute;ographiques sur les Services, sites Web et applications, ou toute autre restriction l&eacute;gale, contractuelle ou technique s'appliquant &agrave; l'activit&eacute; en ligne.</span></p>
<p><span style="font-weight: 400;">Le grattage de toute information contenue dans les Services, par l'utilisation de syst&egrave;mes ou de logiciels automatis&eacute;s pour extraire des donn&eacute;es, y compris tout Contenu et toute information de tiers accessible via les Services, est strictement interdit.</span></p>
<p><span style="font-weight: 400;">Vous ne pouvez pas utiliser les Services ou le Contenu d'une mani&egrave;re ill&eacute;gale, nuisible ou pouvant &ecirc;tre consid&eacute;r&eacute;e comme offensante par transfusio et ses partenaires, d'autres utilisateurs ou des tiers. Vous acceptez de ne pas exploiter les Services ou le Contenu de quelque mani&egrave;re non autoris&eacute;e que ce soit, y compris, mais sans s'y limiter, en p&eacute;n&eacute;trant ou en surchargeant la capacit&eacute; du r&eacute;seau. Vous acceptez en outre de ne pas utiliser nos services ou notre contenu de quelque mani&egrave;re que ce soit pour harceler, abuser, traquer, menacer, diffamer ou autrement enfreindre ou violer les droits de toute autre partie, et vous reconnaissez et acceptez que transfusio n'est en aucun cas responsable de tout une telle utilisation par Vous, ni pour tout message ou transmission de harc&egrave;lement, mena&ccedil;ant, diffamatoire, offensant ou ill&eacute;gal que vous pourriez recevoir &agrave; la suite de l'utilisation des Services. Nonobstant tout autre recours dont dispose transfusio, vous acceptez que transfusio puisse suspendre ou mettre fin &agrave; votre utilisation des services sans pr&eacute;avis si vous utilisez les services ou le contenu de mani&egrave;re interdite, et qu'une telle utilisation sera consid&eacute;r&eacute;e comme une violation substantielle des pr&eacute;sentes conditions.</span></p>
<p><span style="font-weight: 400;">Vous ne pouvez pas utiliser ou autrement exporter ou r&eacute;exporter les Services, sauf dans la mesure autoris&eacute;e par la loi des pays d&rsquo;Afrique et les lois de la juridiction dans laquelle les Services ont &eacute;t&eacute; obtenus. En particulier, mais sans limitation, les Services ne peuvent pas &ecirc;tre export&eacute;s, r&eacute;export&eacute;s ou autrement mis &agrave; disposition (a) dans tout pays ou r&eacute;gion soumis &agrave; un embargo par le gouvernement togolais, ou (b) &agrave; toute personne figurant sur la liste des ressortissants sp&eacute;cialement d&eacute;sign&eacute;s ou la liste des personnes refus&eacute;es ou la liste des entit&eacute;s du minist&egrave;re du Commerce du Togo. En utilisant les Services, vous d&eacute;clarez et garantissez que vous n'&ecirc;tes pas situ&eacute; dans un tel pays ou sur une telle liste. Si vous obtenez l'acc&egrave;s &agrave; des services par abonnement en violation des pr&eacute;sentes conditions, nous nous r&eacute;servons le droit d'annuler cet abonnement sans aucun remboursement des frais conform&eacute;ment &agrave; la loi applicable.</span></p>
<p><span style="font-weight: 400;">Vous pouvez contacter transfusio &agrave; support@nsaatech.com pour signaler toute violation ou violation de vos droits par les utilisateurs des services.</span></p>
<h2><strong>5. DROITS DE PROPRI&Eacute;T&Eacute;</strong></h2>
<p><span style="font-weight: 400;">Les Services sont prot&eacute;g&eacute;s par les lois sur le droit d'auteur et les trait&eacute;s internationaux sur le droit d'auteur, ainsi que par d'autres lois et trait&eacute;s sur la propri&eacute;t&eacute; intellectuelle. transfusio et ses conc&eacute;dants de licence conserveront la propri&eacute;t&eacute; des Services et de tous les droits de propri&eacute;t&eacute; intellectuelle associ&eacute;s, y compris, sans limitation, les droits d'auteur, les marques d&eacute;pos&eacute;es, les noms commerciaux, les droits de base de donn&eacute;es et les brevets. Vous ne disposez que d'un droit limit&eacute; d'utilisation des Services soumis aux pr&eacute;sentes Conditions et aucun droit de propri&eacute;t&eacute; intellectuelle n'est ou ne sera r&eacute;put&eacute; vous avoir &eacute;t&eacute; transf&eacute;r&eacute; ou conc&eacute;d&eacute; sous licence, sauf dans les cas pr&eacute;vus dans les pr&eacute;sentes.</span></p>
<h2><strong>6. CONTENU</strong></h2>
<p><span style="font-weight: 400;">Vous &ecirc;tes seul responsable de tout contenu que vous publiez ou communiquez directement dans ou sur les Services et vous acceptez de publier ou de communiquer uniquement du contenu qui :</span></p>
<ol>
<li style="font-weight: 400;"><span style="font-weight: 400;">est vrai et non faux ou trompeur ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">n'est pas susceptible d'&ecirc;tre consid&eacute;r&eacute; comme mena&ccedil;ant, d&eacute;nigrant, diffamatoire, pornographique, raciste ou ethniquement offensant, discriminatoire, insultant, calomnieux ou autrement ill&eacute;gal ou inappropri&eacute; ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">vous appartient, ou que vous avez le droit de distribuer ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">ne constitue pas une violation des droits de propri&eacute;t&eacute; intellectuelle ou des droits &agrave; la vie priv&eacute;e d'un tiers ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">ne constitue pas une information que vous n&rsquo;&ecirc;tes pas l&eacute;galement autoris&eacute; &agrave; diffuser (telle que des informations privil&eacute;gi&eacute;es ou des informations confidentielles) ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">ne contient aucune publicit&eacute; non sollicit&eacute;e ou non autoris&eacute;e, mat&eacute;riel promotionnel, &laquo; courrier ind&eacute;sirable &raquo;, &laquo; spam &raquo;, &laquo; cha&icirc;nes de lettres &raquo;, &laquo; syst&egrave;mes pyramidaux &raquo; ou toute autre forme de sollicitation ; et</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">ne contient pas de virus logiciel ou toute autre technologie susceptible de nuire aux Services, ou aux int&eacute;r&ecirc;ts ou &agrave; la propri&eacute;t&eacute; de nos Services ou des autres Utilisateurs des Services.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">est exact, juste et ne d&eacute;nigre pas nous-m&ecirc;mes, les Services ou les autres Utilisateurs. De plus, vous acceptez d'&ecirc;tre juste, pr&eacute;cis et non d&eacute;nigrant lorsque vous signalez des chiffres, laissez des commentaires, des suggestions, des commentaires, des t&eacute;moignages et des critiques sur ou &agrave; propos des Services.</span></li>
</ol>
<p><span style="font-weight: 400;">transfusio appr&eacute;cie la possibilit&eacute; d'&ecirc;tre inform&eacute; de tout contenu r&eacute;pr&eacute;hensible g&eacute;n&eacute;r&eacute; par un utilisateur, publi&eacute; ou communiqu&eacute; par un utilisateur directement dans ou sur les Services. Veuillez nous contacter &agrave; support@migbloin.tg pour signaler tout contenu r&eacute;pr&eacute;hensible g&eacute;n&eacute;r&eacute; par l'utilisateur. transfusio se r&eacute;serve par la pr&eacute;sente le droit, &agrave; son enti&egrave;re discr&eacute;tion, de supprimer tout contenu g&eacute;n&eacute;r&eacute; par l'utilisateur des services.</span></p>
<h2><strong>7. CONTENU DE TIERS</strong></h2>
<p><span style="font-weight: 400;">Les Services peuvent contenir des liens vers du contenu externe fourni par des sites Web et services tiers. Ces contenus, sites Web et services tiers peuvent &ecirc;tre soumis aux conditions g&eacute;n&eacute;rales respectives des tiers et transfusio ne sera pas responsable de ces contenus, sites Web ou services tiers.</span></p>
<h2><strong>8. EXCLUSION DE GARANTIES</strong></h2>
<p><span style="font-weight: 400;">DANS LA MESURE MAXIMALE PERMISE PAR LA LOI APPLICABLE, transfusio NE FAIT AUCUNE GARANTIE OU D&Eacute;CLARATION, EXPRESSE OU IMPLICITE, CONCERNANT LES SERVICES, LEUR QUALIT&Eacute;, PERFORMANCE, QUALIT&Eacute; MARCHANDE, AD&Eacute;QUATION &Agrave; UN USAGE PARTICULIER OU NON-VIOLATION DES DROITS DE TIERS. LES SERVICES SONT FOURNIS &laquo; EN L'&Eacute;TAT &raquo; ET VOUS ACCEPTEZ QUE LES SERVICES SONT UTILIS&Eacute;S &Agrave; VOS PROPRES RISQUES.</span></p>
<p><span style="font-weight: 400;">Vous comprenez et reconnaissez que les Services peuvent &ecirc;tre indisponibles de temps &agrave; autre et que transfusio ne sera pas responsable de votre incapacit&eacute; &agrave; utiliser les Services pour quelque raison que ce soit.</span></p>
<p><span style="font-weight: 400;">transfusio ne donne aucune garantie ni repr&eacute;sentation selon laquelle les services sont disponibles pour une utilisation dans un endroit particulier. Dans la mesure o&ugrave; vous choisissez d'acc&eacute;der et d'utiliser les services, vous le faites de votre propre initiative et &ecirc;tes responsable du respect de toutes les lois applicables en relation avec cet acc&egrave;s et cette utilisation des services.</span></p>
<h2><strong>9. LIMITATION DE RESPONSABILIT&Eacute;</strong></h2>
<p><span style="font-weight: 400;">DANS LA MESURE MAXIMALE PERMISE PAR LA LOI APPLICABLE, VOUS ACCEPTEZ EXPRESS&Eacute;MENT QUE transfusio NE SERA EN AUCUN CAS &Ecirc;TRE RESPONSABLE DE TOUT DOMMAGE DIRECT, INDIRECT, SP&Eacute;CIAL, ACCESSOIRE, CONS&Eacute;CUTIF OU EXEMPLAIRE, Y COMPRIS MAIS SANS LIMITATION LES DOMMAGES POUR PERTE DE PROFITS, DE DONN&Eacute;ES ET DE FONDS DE COMMERCE, D&Eacute;COULANT DE L'UTILISATION OU DE L'INCAPACIT&Eacute; &Agrave; UTILISER LES SERVICES OU LE CONTENU, m&ecirc;me s'il est inform&eacute; de la possibilit&eacute; de tels dommages. En particulier, et sans limitation, transfusio ne pourra &ecirc;tre tenu responsable de toute information stock&eacute;e ou trait&eacute;e dans le cadre des Services, y compris les co&ucirc;ts de r&eacute;cup&eacute;ration de ces informations. Votre seul droit ou recours en cas de probl&egrave;me ou d'insatisfaction concernant les Services est de d&eacute;sinstaller les applications MiGbloin et de cesser d'utiliser les Services.</span></p>
<p><span style="font-weight: 400;">transfusio NE SERA PAS RESPONSABLE DE LA VALIDIT&Eacute;, DE LA FIABILIT&Eacute; OU DE L'EXACTITUDE DU CONTENU ET DES INFORMATIONS FOURNIES PAR ET EN RELATION AVEC L'UTILISATION DES SERVICES. TOUTE UTILISATION DU CONTENU ET DES INFORMATIONS OBTENUES PAR L'UTILISATION DES SERVICES EST &Agrave; VOTRE PROPRE DISCR&Eacute;TION ET &Agrave; VOS PROPRES RISQUES.</span></p>
<p><span style="font-weight: 400;">Rien dans les pr&eacute;sentes Conditions ne saurait limiter ou exclure notre responsabilit&eacute; pour toute responsabilit&eacute; qui ne peut obligatoirement &ecirc;tre limit&eacute;e ou exclue par la loi, y compris les droits que vous pourriez avoir en tant que consommateur en vertu du droit de la consommation obligatoire.</span></p>
<h2><strong>10. FRAIS</strong></h2>
<p><span style="font-weight: 400;">transfusio ne propose pas encore de fonctionnalit&eacute;s ou services pour lesquels des frais seront payables (&laquo;</span><strong> Services payants</strong><span style="font-weight: 400;"> &raquo;).</span></p>
<p><span style="font-weight: 400;">Vous reconnaissez que vous &ecirc;tes enti&egrave;rement responsable de la connexion Internet et/ou des frais de t&eacute;l&eacute;phonie mobile que vous pourriez engager pour l'utilisation de nos services. Veuillez consulter votre op&eacute;rateur, op&eacute;rateur mobile, etc. pour plus d'informations.</span></p>
<h2><strong>11. R&Eacute;SILIATION</strong></h2>
<p><span style="font-weight: 400;">Votre droit d'utiliser les Services continue jusqu'&agrave; la r&eacute;siliation des pr&eacute;sentes Conditions. transfusio peut r&eacute;silier les Conditions et votre utilisation des Services &agrave; tout moment avec un pr&eacute;avis de trente (30) jours. Vous pouvez r&eacute;silier les Conditions &agrave; tout moment en d&eacute;sinstallant les applications Migbloin et en cessant d'utiliser les Services. Ces Conditions prendront automatiquement fin si Vous ne les respectez pas. En cas de r&eacute;siliation, vous acceptez de cesser d'utiliser les services. En cas de r&eacute;siliation de votre part ou de transfusio en raison de votre violation des pr&eacute;sentes conditions, vous ne serez pas rembours&eacute; des frais de licence ou autres frais pr&eacute;pay&eacute;s, le cas &eacute;ch&eacute;ant. En cas de r&eacute;siliation par transfusio sans motif, vous serez rembours&eacute; de tous les frais pr&eacute;pay&eacute;s non utilis&eacute;s sur votre demande &eacute;crite, &agrave; condition qu'un re&ccedil;u de ces frais et une instruction de paiement claire soient inclus dans votre demande.</span></p>
<p><span style="font-weight: 400;">Les dispositions des sections Exon&eacute;ration de garantie, Limitation de responsabilit&eacute;, R&eacute;siliation et Loi applicable survivront &agrave; toute r&eacute;siliation des pr&eacute;sentes Conditions.</span></p>
<h2><strong>12. MISSION</strong></h2>
<p><span style="font-weight: 400;">transfusio se r&eacute;serve le droit, &agrave; sa propre discr&eacute;tion, de c&eacute;der et de transf&eacute;rer librement les droits et obligations en vertu des pr&eacute;sentes Conditions &agrave; tout tiers.</span></p>
<h2><strong>13. CONDITIONS SUPPL&Eacute;MENTAIRES ET MODIFICATIONS</strong></h2>
<p><span style="font-weight: 400;">&Eacute;tant donn&eacute; que transfusio fournit des services internationaux, des conditions de services suppl&eacute;mentaires peuvent s'appliquer aux utilisateurs dans certaines juridictions et seront dans de tels cas mises &agrave; disposition dans les annexes et incorpor&eacute;es aux pr&eacute;sentes.</span></p>
<p><span style="font-weight: 400;">transfusio peut modifier les services &agrave; tout moment, par exemple en ajoutant ou en supprimant des fonctionnalit&eacute;s ou en interrompant les services. transfusio se r&eacute;serve &eacute;galement le droit de modifier ces Conditions &agrave; tout moment en fournissant des Conditions r&eacute;vis&eacute;es &agrave; l'Utilisateur ou en publiant les Conditions r&eacute;vis&eacute;es dans les Services. En cas de changements importants, l'utilisateur en sera toujours inform&eacute; et aura la possibilit&eacute; de mettre fin imm&eacute;diatement aux services. Si vous choisissez de mettre fin aux services, vous serez rembours&eacute; de tous les frais pr&eacute;pay&eacute;s non utilis&eacute;s sur votre demande &eacute;crite, &agrave; condition qu'un re&ccedil;u de ces frais et des instructions de paiement claires soient inclus dans votre demande. Les Conditions r&eacute;vis&eacute;es entreront en vigueur d&egrave;s cette publication ou notification &agrave; l&rsquo;Utilisateur. Vous trouverez toujours la derni&egrave;re version de ces Conditions sur&nbsp; </span><a href="https://www.truecaller.com/terms-of-service"><span style="font-weight: 400;">https://www.migbloin.tg//</span></a><span style="font-weight: 400;">conditions-generales-utilisation . Toute utilisation continue de votre part des Services apr&egrave;s la publication ou la notification des Conditions r&eacute;vis&eacute;es constituera votre acceptation des Conditions r&eacute;vis&eacute;es.</span></p>
<h2><strong>14. LOI APPLICABLE</strong></h2>
<p><span style="font-weight: 400;">Ces conditions seront r&eacute;gies et interpr&eacute;t&eacute;es conform&eacute;ment aux lois du Togo. Vous acceptez que toute action ou proc&eacute;dure judiciaire puisse &ecirc;tre intent&eacute;e exclusivement devant les tribunaux/tribunaux comp&eacute;tents ayant juridiction &agrave; Lom&eacute;, au Togo et transfusio et vous vous soumettez irr&eacute;vocablement &agrave; la juridiction de ces tribunaux/tribunaux.</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>""",
                    )
                    : const HtmlWidget(
                      """<h1><strong>POLITIQUE DE CONFIDENTIALIT&Eacute; DE transfusio</strong></h1>
<p><span style="font-weight: 400;">Migbloin AntiArnaque a &eacute;t&eacute; cr&eacute;&eacute; pour donner &agrave; nos utilisateurs plus de s&eacute;curit&eacute; sur leurs communications et notre approche est bas&eacute;e sur des principes clairs de confidentialit&eacute;.</span></p>
<p><span style="font-weight: 400;">Aujourd'hui, nous proposons le signalement d&rsquo;un appel frauduleux, l&rsquo;enregistrement d&rsquo;un appel, l'identification de l'appelant, le blocage d&rsquo;un num&eacute;ro et d'autres services pour nos utilisateurs Togo.</span></p>
<p><span style="font-weight: 400;">Cette politique de confidentialit&eacute; d&eacute;crit comment transfusio (&laquo; NsaaTech&raquo;, &laquo; nous &raquo; ou &laquo; notre &raquo;) accepte, collecte, stocke, utilise, transf&egrave;re, partage ou traite de toute autre mani&egrave;re vos informations si vous r&eacute;sidez au Togo.</span></p>
<h2><strong>COMMENT VOUS POUVEZ DONNER VOTRE CONSENTEMENT</strong></h2>
<p><span style="font-weight: 400;">Veuillez noter que les termes de cette politique de confidentialit&eacute; s'appliquent &agrave; votre utilisation ou &agrave; votre utilisation continue de nos services et r&eacute;gissent l'acceptation, la collecte, le stockage, l'utilisation, le transfert, le partage ou tout autre traitement de vos informations comme d&eacute;crit ici et dans les conditions de service et par En cliquant sur l'onglet &laquo; COMMENCER &raquo; sur la page d'inscription de l'application, vous consentez &agrave; l'application des termes de la pr&eacute;sente politique de confidentialit&eacute; et des conditions d'utilisation &agrave; votre utilisation de nos services. Pour plus de clart&eacute;, nous avons superpos&eacute; cette politique de confidentialit&eacute; en incluant des hyperliens qui vous fournissent des informations plus d&eacute;taill&eacute;es, un contexte et des exemples suppl&eacute;mentaires, et ces informations font partie de cette politique de confidentialit&eacute;.</span></p>
<h2><strong>D&Eacute;CLARATION DE CONFORMIT&Eacute; AUX PRINCIPES DE PROTECTION DES DONN&Eacute;ES</strong></h2>
<p><span style="font-weight: 400;">Nous recevons vos donn&eacute;es aux fins sp&eacute;cifiques indiqu&eacute;es dans cette politique de confidentialit&eacute; visant &agrave; activer notre service de signalement d&rsquo;un appel frauduleux, l&rsquo;enregistrement d&rsquo;un appel, l'identification de l'appelant, le blocage d&rsquo;un num&eacute;ro plus sp&eacute;cifiquement d&eacute;taill&eacute;s dans cette politique de confidentialit&eacute;. Vos donn&eacute;es personnelles sont stock&eacute;es en toute s&eacute;curit&eacute; sur notre serveur et nous prenons des mesures pour garantir la s&eacute;curit&eacute; de vos donn&eacute;es en mettant en &oelig;uvre des garanties physiques, &eacute;lectroniques et proc&eacute;durales afin de prot&eacute;ger les informations, y compris le stockage des informations sur des serveurs s&eacute;curis&eacute;s prot&eacute;g&eacute;s par des r&eacute;seaux s&eacute;curis&eacute;s auxquels l&rsquo;acc&egrave;s est limit&eacute; &agrave; quelques employ&eacute;s et personnels autoris&eacute;s. Vos donn&eacute;es sont stock&eacute;es pendant la dur&eacute;e de votre abonnement &agrave; notre service et si vous choisissez de d&eacute;sactiver votre compte, nous supprimons vos donn&eacute;es de notre serveur.</span></p>
<h2><strong>INFORMATIONS DISPONIBLES POUR NOUS</strong></h2>
<p><span style="font-weight: 400;">Lorsque vous installez, acc&eacute;dez ou utilisez nos services, nous pouvons traiter les cat&eacute;gories d'informations suivantes aux fins d&eacute;crites ci-dessous.</span></p>
<h2><strong>INFORMATIONS QUE VOUS NOUS DONNEZ</strong></h2>
<p><strong>Compte et profil utilisateur. </strong><span style="font-weight: 400;">Nous acceptons votre nom et votre num&eacute;ro de t&eacute;l&eacute;phone portable pour cr&eacute;er votre compte utilisateur et votre profil. Vous pouvez &eacute;galement choisir de fournir des informations suppl&eacute;mentaires pour votre profil d'utilisateur telles que photo et adresse e-mail.</span></p>
<p><strong>SMS. </strong><span style="font-weight: 400;">Si vous avez donn&eacute; votre consentement , nous acc&eacute;dons &agrave; vos SMS (mais sans r&eacute;v&eacute;ler leur contenu) pour identifier les messages de validation de num&eacute;ro de t&eacute;l&eacute;phone (code OTP).</span></p>
<p><strong>Carnet d'adresses. </strong><span style="font-weight: 400;">Si vous avez donn&eacute; votre consentement , nous acc&eacute;dons aux contacts de votre carnet d'adresses . En accordant un tel acc&egrave;s, vous confirmez que vous &ecirc;tes autoris&eacute; &agrave; partager les informations de votre carnet d'adresses avec nous. Si l'application Migbloin Antiarnaque est t&eacute;l&eacute;charg&eacute;e depuis l'App Store d'Apple ou Google Play, nous ne recevons, ne stockons ni ne partageons aucune des informations de contact de votre carnet d'adresses.</span></p>
<p><strong>Support client et enqu&ecirc;tes. </strong><span style="font-weight: 400;">Si vous nous contactez au sujet de votre exp&eacute;rience d'utilisation de nos services, nous utiliserons les informations que vous avez fournies pour r&eacute;pondre et r&eacute;soudre les probl&egrave;mes, par exemple lorsque vous nous contactez par e-mail. Vous pouvez &eacute;galement nous fournir des informations si vous d&eacute;cidez de participer &agrave; des concours et &agrave; des enqu&ecirc;tes, ou sous r&eacute;serve de vos param&egrave;tres, si nous vous envoyons des offres sp&eacute;ciales et des promotions.</span></p>
<h2><strong>INFORMATIONS QUE NOUS RECEVONS LORSQUE VOUS UTILISEZ NOS SERVICES</strong></h2>
<p><strong>Informations sur l'appareil et la connexion. </strong><span style="font-weight: 400;">Nous collectons les informations relatives &agrave; votre appareil et &agrave; votre connexion ainsi que des identifiants uniques afin que vous puissiez vous connecter et utiliser nos Services. Les informations sur l'appareil et la connexion d&eacute;signent le fabricant et le mod&egrave;le de l'appareil, les param&egrave;tres de l'appareil, le syst&egrave;me d'exploitation, la version des services, l'adresse IP, les informations de connexion, les informations SIM (y compris IMSI), le navigateur Web, la r&eacute;solution d'&eacute;cran et les applications install&eacute;es sur votre appareil, vos appareils coupl&eacute;s ( comme une montre intelligente).</span></p>
<p><span style="font-weight: 400;">Nous avons besoin d'acc&eacute;der aux informations sur les appareils et les connexions pour : (a) surveiller nos syst&egrave;mes afin de garantir qu'ils fonctionnent comme pr&eacute;vu ; (b) identifier et r&eacute;soudre tous les probl&egrave;mes et bogues qui peuvent affecter uniquement un type de fabricant ou un type d'appareil ; (c) identifier &agrave; partir de l'IMEI le r&eacute;seau auquel appartient un num&eacute;ro de mobile et nous permettre de traiter les probl&egrave;mes de service li&eacute;s au r&eacute;seau ; (d) comprendre l'utilisation de la carte SIM pour les t&eacute;l&eacute;phones mobiles &eacute;quip&eacute;s de deux cartes SIM afin de d&eacute;terminer quelle carte SIM doit &ecirc;tre utilis&eacute;e pour activer les services et quelle carte SIM doit &ecirc;tre utilis&eacute;e pour la communication par l'application ; (e) pour la s&eacute;curit&eacute; et la d&eacute;tection des fraudes en identifiant des mod&egrave;les d'utilisation inhabituels ; (f) comprendre si vous avez activ&eacute; les notifications et la localisation afin que nous puissions nous conformer &agrave; vos choix ; (g) indiquer la date de votre derni&egrave;re connexion (&laquo; statut de derni&egrave;re connexion &raquo; ); (h) activer et d&eacute;sactiver des fonctionnalit&eacute;s dans notre application.</span></p>
<p><span style="font-weight: 400;">Les identifiants uniques sont un certain nombre de caract&egrave;res utilis&eacute;s pour identifier un appareil, une application ou un navigateur. Certains sont permanents et d'autres peuvent &ecirc;tre r&eacute;initialis&eacute;s &agrave; tout moment par les utilisateurs sur leurs appareils comme l'ID publicitaire. Les fabricants peuvent &eacute;galement int&eacute;grer d'autres identifiants universellement uniques (tels qu'un num&eacute;ro IMEI) dans un appareil. Nous utilisons des identifiants uniques &agrave; diverses fins, notamment pour m&eacute;moriser vos pr&eacute;f&eacute;rences, d&eacute;tecter la fraude, la s&eacute;curit&eacute;, personnaliser les services ou analyser les probl&egrave;mes li&eacute;s &agrave; l'appareil, et en fonction de vos param&egrave;tres, pour vous montrer des publicit&eacute;s personnalis&eacute;es.</span></p>
<p><strong>Information de Lieu. </strong><span style="font-weight: 400;">Si vous avez donn&eacute; votre consentement , nous pouvons collecter des informations sur la position pr&eacute;cise de votre appareil &agrave; l'aide du GPS, des tours de t&eacute;l&eacute;phonie cellulaire, des balises et des points d'acc&egrave;s Wi-Fi, par exemple, pour activer des fonctionnalit&eacute;s utilisateur telles que le partage de votre position via des messages ou la fourniture de r&eacute;sultats de recherche plus pertinents. Vous pouvez &eacute;galement contr&ocirc;ler &agrave; tout moment si vous souhaitez partager votre position dans les param&egrave;tres de votre appareil ( appareils Android, appareils Apple ). Nous n'utilisons pas votre localisation pr&eacute;cise pour des publicit&eacute;s cibl&eacute;es.</span></p>
<p><strong>Informations sur les journaux et les &eacute;v&eacute;nements. </strong><span style="font-weight: 400;">Vous acceptez que lorsque vous utilisez les Services, nous puissions collecter des informations sur les journaux et les &eacute;v&eacute;nements, telles que la fa&ccedil;on dont vous utilisez nos Services, les configurez, y acc&eacute;dez et comment vous interagissez avec d'autres utilisateurs et num&eacute;ros, notamment en les marquant, en les bloquant, en les appelant, ou l'envoi de demandes de contact. Nous enregistrons les &eacute;v&eacute;nements (par exemple, pour remplir votre liste &laquo; Appels r&eacute;cents &raquo;) et collectons &eacute;galement des rapports et des journaux sur les performances, les diagnostics, les sites Web, les bogues et les plantages. Cela nous permet de fournir nos Services de mani&egrave;re efficace et d&rsquo;am&eacute;liorer leur qualit&eacute;.</span></p>
<p><strong>Cookies. </strong><span style="font-weight: 400;">Nous collectons automatiquement certaines informations vous concernant gr&acirc;ce &agrave; l'utilisation de cookies afin d'exploiter et de fournir nos services, y compris le service Web Migbloin Antiarnaque. Vous pouvez en savoir plus sur le type d'informations que nous collectons aupr&egrave;s de vous &agrave; l'aide de cookies, la raison pour laquelle nous collectons ces informations et la mani&egrave;re dont vous pouvez contr&ocirc;ler les cookies via les param&egrave;tres du navigateur dans notre Politique en mati&egrave;re de cookies.</span></p>
<h2><strong>INFORMATIONS DE TIERS</strong></h2>
<p><span style="font-weight: 400;">Nous recevons des informations vous concernant de tiers lorsque vous vous inscrivez aux Services ou mettez &agrave; jour les informations de votre profil &agrave; l'aide de services tiers tels que des comptes de r&eacute;seaux sociaux, ainsi que d'autres utilisateurs. Par exemple, d'autres utilisateurs peuvent marquer votre num&eacute;ro &agrave; l'aide d'une liste de descriptions ou associer n'importe quel num&eacute;ro de t&eacute;l&eacute;phone &agrave; une entreprise ou &agrave; un nom, ou encore le bloquer et le signaler &agrave; d'autres comme spam via notre plateforme.</span></p>
<p><span style="font-weight: 400;">Vous pouvez &eacute;galement utiliser nos Services en relation avec des services tiers. Afin que les Services interagissent avec ces services tiers, nous pouvons recevoir des informations de leur part sur vous ou nous pouvons partager vos informations avec eux. Par exemple, vous pouvez vous connecter &agrave; nos Services &agrave; l'aide de services tiers ou cr&eacute;er un compte sur une plateforme tierce en utilisant nos Services pour pr&eacute;-remplir vos informations afin de vous inscrire aupr&egrave;s d'eux ou vous pouvez connecter votre profil d'utilisateur &agrave; des services tiers. . En vous connectant &agrave; nos Services &agrave; l'aide de services tiers ou en cr&eacute;ant un compte sur une plateforme tierce utilisant nos Services ou en connectant de toute autre mani&egrave;re votre profil d'utilisateur sur nos Services &agrave; des services tiers, vous acceptez que nous puissions : (a) collecter, accepter , utilisez et conservez les informations fournies par ces services tiers conform&eacute;ment &agrave; la pr&eacute;sente politique de confidentialit&eacute;, et (b) compl&eacute;tez vos informations d'utilisateur si, par exemple, vous choisissez de cr&eacute;er votre compte ou de mettre &agrave; jour les informations de votre profil en utilisant Facebook, Google ou Microsoft. Ces tiers ne partagent ces informations qu'avec votre consentement pr&eacute;alable et sur la base de leurs conditions de confidentialit&eacute;. Nous ne stockons jamais les mots de passe cr&eacute;&eacute;s pour des services tiers. Votre utilisation de services tiers est r&eacute;gie par les conditions et politiques de confidentialit&eacute; de ces services.</span></p>
<h2><strong>INFORMATIONS NON PERSONNELLES</strong></h2>
<p><strong>Utilisateurs. </strong><span style="font-weight: 400;">Certaines informations, y compris les informations d'utilisation et d'autres informations pouvant d&eacute;couler de votre interaction avec les Services, ne peuvent pas &ecirc;tre utilis&eacute;es pour vous identifier, que ce soit en combinaison avec d'autres informations ou autrement et ne constitueront pas des informations personnelles aux fins de cette politique.</span></p>
<p><strong>Profils d'entreprise. </strong><span style="font-weight: 400;">Une entreprise peut cr&eacute;er un profil pour rendre ses informations commerciales (y compris son nom commercial ou commercial, son num&eacute;ro de t&eacute;l&eacute;phone, son adresse &eacute;lectronique, son adresse, ses heures d'ouverture et ses identifiants de r&eacute;seaux sociaux) accessibles au public aux utilisateurs de la plateforme Migbloin Antiarnaque. Ces informations ne constitueront pas des informations personnelles aux fins de la pr&eacute;sente politique et les conditions du profil d'entreprise s'appliqueront.</span></p>
<h2><strong>COMMENT NOUS UTILISONS LES INFORMATIONS PERSONNELLES</strong></h2>
<p><span style="font-weight: 400;">Nous utilisons les informations pour fournir, exploiter, maintenir, prendre en charge, am&eacute;liorer, comprendre, commercialiser et personnaliser nos services pour vous des mani&egrave;res suivantes.</span></p>
<p><strong>Prestations de service. </strong><span style="font-weight: 400;">Nous utilisons vos informations pour fournir et exploiter nos services, notamment :</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">vous aider &agrave; communiquer via nos Services et vous identifier lorsque vous contactez d'autres personnes ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">pour v&eacute;rifier votre nom et votre num&eacute;ro de t&eacute;l&eacute;phone portable et attribuer un &laquo; badge de v&eacute;rification &raquo; lors de leur validation ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">cat&eacute;goriser et bloquer les appels pour vous ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">en fonction de vos param&egrave;tres, fournissant des notifications push, des notifications SMS intelligentes et des rappels ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">vous aider &agrave; identifier lesquels de vos contacts utilisent &eacute;galement Migbloin Antiarnaque ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">cr&eacute;er et analyser des informations agr&eacute;g&eacute;es sur les mod&egrave;les d'appel et l'utilisation des Services et permettre aux utilisateurs de bloquer ou de signaler des num&eacute;ros comme spam pour cr&eacute;er et mettre &agrave; disposition un r&eacute;pertoire de blocage de spam bas&eacute; sur les commentaires de la communaut&eacute; d'utilisateurs, une liste de spam et des informations contextuelles associ&eacute;es pour aider les utilisateurs &agrave; d&eacute;tecter et &agrave; pr&eacute;venir les activit&eacute;s ill&eacute;gales ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">permettre aux utilisateurs de rechercher des entreprises enregistr&eacute;es aupr&egrave;s de Migbloin Antiarnaque ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">fournir un support client, r&eacute;pondre &agrave; vos requ&ecirc;tes, enqu&ecirc;ter et r&eacute;soudre les probl&egrave;mes li&eacute;s aux Services ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">am&eacute;liorer, r&eacute;parer et personnaliser nos services ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">comprendre comment nos utilisateurs utilisent nos Services ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">analyser et utiliser les informations pour &eacute;valuer et am&eacute;liorer nos services, nos activit&eacute;s et nos op&eacute;rations ;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">d&eacute;velopper ou fournir des services &agrave; des tiers ou am&eacute;liorer les services de tiers ; et</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">rechercher, d&eacute;velopper et tester de nouveaux services et fonctionnalit&eacute;s.</span></li>
</ul>
<p><strong>S&ucirc;ret&eacute; et s&eacute;curit&eacute;. </strong><span style="font-weight: 400;">Nous utilisons vos informations pour nous conformer aux lois applicables, v&eacute;rifier les comptes et l'activit&eacute; des utilisateurs, garantir la fonctionnalit&eacute; du service, la s&eacute;curit&eacute; et l'exactitude des donn&eacute;es, enqu&ecirc;ter sur les activit&eacute;s suspectes et faire respecter nos accords, effectuer des activit&eacute;s de d&eacute;pannage et pr&eacute;venir la fraude, les failles de s&eacute;curit&eacute; et le contournement de l'utilisation pr&eacute;vue de nos services, nos conditions d'utilisation , cette politique de confidentialit&eacute; et les activit&eacute;s restreintes, interdites ou ill&eacute;gales.</span></p>
<p><strong>Services tiers. </strong><span style="font-weight: 400;">Avec votre consentement , nous vous permettons d'utiliser et de partager vos informations pour vous inscrire et vous connecter &agrave; des services tiers ou pour que vous puissiez utiliser nos services en relation avec d'autres services tiers. Par exemple, pour utiliser des services de r&eacute;seaux sociaux. Si vous utilisez un service tiers via un lien dans nos Services, vous pouvez fournir des informations directement &agrave; ce tiers. Dans de tels cas, les conditions et politiques de confidentialit&eacute; du service tiers s&rsquo;appliqueront &agrave; votre utilisation de leurs services. Vous pouvez &eacute;galement choisir d'acc&eacute;der &agrave; nos Services via la promotion de nos Services par un tiers.</span></p>
<p><strong>Fournisseurs de services tiers. </strong><span style="font-weight: 400;">Nous faisons appel &agrave; des prestataires de services tiers pour prendre en charge nos services et nos activit&eacute;s. Par exemple, nous faisons appel &agrave; des tiers pour distribuer notre application et pour fournir des services de v&eacute;rification, des services d'infrastructure, des services de publicit&eacute;, des services de marketing, un support client, des tests de bogues, analyser la fa&ccedil;on dont nos services sont utilis&eacute;s, mesurer l'efficacit&eacute; des publicit&eacute;s et des services, faciliter les paiements, et mener des enqu&ecirc;tes et des recherches. Nous demandons &agrave; ces tiers de prendre les mesures organisationnelles et techniques appropri&eacute;es pour prot&eacute;ger vos informations et respecter les lois applicables.</span></p>
<p><strong>Donn&eacute;e statistique. </strong><span style="font-weight: 400;">Nous utilisons des informations agr&eacute;g&eacute;es, anonymis&eacute;es ou anonymis&eacute;es &agrave; des fins statistiques et analytiques. Nous pouvons partager ces donn&eacute;es avec des tiers. Nous ne consid&eacute;rons pas que les informations personnelles incluent les informations anonymis&eacute;es, rendues anonymes ou regroup&eacute;es de sorte qu'elles ne puissent plus &ecirc;tre utilis&eacute;es pour identifier une personne sp&eacute;cifique, directement ou en combinaison avec d'autres informations ou moyens raisonnablement susceptibles d'&ecirc;tre &agrave; notre disposition. Nous pouvons fournir des services de mesure et d'analyse (en utilisant ces informations) afin d'aider les entreprises &agrave; mieux comprendre l'efficacit&eacute; de leurs interactions avec nos utilisateurs sur nos Services, leur engagement et la distribution de leurs produits et services.</span></p>
<h2><strong>COMMENT NOUS PERMETTONS LE PARTAGE D'INFORMATIONS</strong></h2>
<p><span style="font-weight: 400;">Nous permettons le partage d'informations pour fournir, exploiter, maintenir, prendre en charge, am&eacute;liorer, comprendre ou personnaliser nos services, notamment des mani&egrave;res suivantes :</span></p>
<p><strong>Services tiers. </strong><span style="font-weight: 400;">Avec votre consentement , nous vous permettons d'utiliser et de partager vos informations pour vous inscrire, vous connecter ou utiliser des services tiers. Par exemple, vous partagez vos informations avec Google si vous choisissez de sauvegarder vos donn&eacute;es sur Google Drive. Si vous utilisez un service tiers via un lien dans nos Services, vous pouvez partager des informations directement avec ce tiers. Dans de tels cas, les conditions et politiques de confidentialit&eacute; du tiers s&rsquo;appliqueront &agrave; ces informations et &agrave; votre utilisation de leurs services.</span></p>
<p><strong>Fournisseurs de services tiers. </strong><span style="font-weight: 400;">Nous faisons appel &agrave; des prestataires de services tiers de confiance pour prendre en charge nos services et nos activit&eacute;s. Lorsque nous partageons des informations avec de tels tiers, nous leur demandons de prendre les mesures organisationnelles et techniques appropri&eacute;es pour prot&eacute;ger vos informations et respecter les lois applicables.</span></p>
<p><strong>Droit et s&eacute;curit&eacute;. </strong><span style="font-weight: 400;">Nous pouvons divulguer vos informations si nous pensons qu'une telle action est n&eacute;cessaire pour : (a) nous conformer aux lois applicables, aux demandes gouvernementales ou &agrave; la proc&eacute;dure judiciaire qui nous est impos&eacute;e ; (b) prot&eacute;ger et d&eacute;fendre nos droits et l'application de nos accords, notamment pour garantir la fonctionnalit&eacute; du service technique, l'exactitude des donn&eacute;es, effectuer un d&eacute;pannage, prot&eacute;ger notre plate-forme et nos services contre les abus, et pr&eacute;venir ou d&eacute;tecter les failles de s&eacute;curit&eacute; et les activit&eacute;s ill&eacute;gales, restreintes ou interdites. ; et (c) prot&eacute;ger la s&eacute;curit&eacute; et la s&ucirc;ret&eacute; des utilisateurs ou des membres du public ou d'autres aspects d'importance publique &agrave; condition qu'une telle divulgation soit licite.</span></p>
<p><strong>Acquisitions et transfert. </strong><span style="font-weight: 400;">Nous pouvons divulguer et transf&eacute;rer vos informations ou nos obligations et droits en vertu de la pr&eacute;sente politique de confidentialit&eacute; &agrave; un de nos partenaires techniques dans la lutte contre les arnaques.</span></p>
<h2><strong>BASES JURIDIQUES ET CONSERVATION DES DONN&Eacute;ES</strong></h2>
<p><span style="font-weight: 400;">Nous collectons, utilisons et partageons vos informations conform&eacute;ment &agrave; nos Conditions d'utilisation (par exemple, pour fournir les Services), y compris sur la base de votre consentement, de l'utilisation de nos Services et des choix que vous faites lors de l'inscription et dans vos param&egrave;tres ou sur la base de la protection de vos int&eacute;r&ecirc;ts vitaux ou ceux d&rsquo;une autre personne physique ou fond&eacute;s sur l&rsquo;int&eacute;r&ecirc;t public. Nous garantissons que le traitement des donn&eacute;es effectu&eacute; &agrave; ces fins est n&eacute;cessaire &agrave; la protection d'int&eacute;r&ecirc;ts vitaux (par exemple, en identifiant les personnes qui vous contactent) ou &agrave; l'ex&eacute;cution de t&acirc;ches effectu&eacute;es dans l'int&eacute;r&ecirc;t public (par exemple, en identifiant les appels frauduleux et en fournissant des informations contextuelles), pour d&eacute;tecter et pr&eacute;venir les activit&eacute;s ill&eacute;gales, et que cela l'emporte sur tout int&eacute;r&ecirc;t &agrave; ne pas que les donn&eacute;es soient trait&eacute;es &agrave; de telles fins. Lorsque nous traitons des donn&eacute;es sur la seule base de votre consentement, vous pouvez retirer votre consentement &agrave; tout moment via vos param&egrave;tres. Nous collectons, traitons et conservons &eacute;galement vos informations pour nous conformer aux lois applicables et &agrave; nos obligations l&eacute;gales.</span></p>
<p><span style="font-weight: 400;">transfusio conservera vos informations aussi longtemps que vous conserverez un profil d'utilisateur dans les Services et comme indiqu&eacute; ci-dessous. Vous pouvez &agrave; tout moment choisir de d&eacute;sactiver votre compte et de supprimer votre profil utilisateur et vos informations via vos param&egrave;tres. Si vous d&eacute;sactivez votre compte, nous supprimons de nos serveurs toutes vos informations dont nous n'avons pas besoin pour fournir nos Services. Nous conserverons vos informations pendant la p&eacute;riode n&eacute;cessaire pour atteindre les objectifs d&eacute;crits dans notre politique de confidentialit&eacute;, &agrave; moins qu'une p&eacute;riode de conservation plus longue ne soit requise ou autoris&eacute;e par la loi.&nbsp;</span></p>
<h2><strong>S&Eacute;CURIT&Eacute; ET TRANSFERT D'INFORMATIONS</strong></h2>
<p><span style="font-weight: 400;">Les Services n&eacute;cessitent, de par leur nature m&ecirc;me, que vos informations puissent &ecirc;tre transf&eacute;r&eacute;es &agrave; d'autres partenaires pour une fourniture efficace des Services. transfusio peut utiliser des services bas&eacute;s sur le cloud et sous-traiter le stockage ou le traitement de vos informations &agrave; des tiers situ&eacute;s dans des pays autres que votre pays d'origine afin de fournir les services, comme la Suisse ou les &Eacute;tats-Unis. Les informations &eacute;manant d'un pays peuvent par exemple &ecirc;tre transf&eacute;r&eacute;es et trait&eacute;es dans un autre pays.</span></p>
<p><span style="font-weight: 400;">Nous prenons toutes les pr&eacute;cautions raisonnables pour prot&eacute;ger les informations personnelles contre toute utilisation abusive, perte et acc&egrave;s non autoris&eacute;, notamment en exigeant que les destinataires d'informations situ&eacute;s dans d'autres pays se conforment aux exigences contractuelles en mati&egrave;re de protection des donn&eacute;es.&nbsp;</span></p>
<p><span style="font-weight: 400;">Nous avons mis en &oelig;uvre des mesures de protection physiques, &eacute;lectroniques et proc&eacute;durales afin de prot&eacute;ger les informations, notamment le fait que les informations seront stock&eacute;es sur des serveurs s&eacute;curis&eacute;s et prot&eacute;g&eacute;es par des r&eacute;seaux s&eacute;curis&eacute;s dont l'acc&egrave;s est limit&eacute; &agrave; quelques employ&eacute;s et personnels autoris&eacute;s. Cependant, aucune m&eacute;thode de transmission sur Internet ni aucune m&eacute;thode de stockage &eacute;lectronique n&rsquo;est s&eacute;curis&eacute;e &agrave; 100 %. En cas de violation, votre recours sera conforme aux conditions d&rsquo;utilisation. Vous reconnaissez et acceptez que transfusio puisse transf&eacute;rer vos informations comme d&eacute;crit ci-dessus &agrave; des fins conformes &agrave; cette politique.</span></p>
<h2><strong>ACC&Egrave;S ET CONTR&Ocirc;LE DE VOS INFORMATIONS</strong></h2>
<p><span style="font-weight: 400;">Migbloin Antiarnaque vous propose de nombreux choix pour g&eacute;rer vos informations. Par exemple, vous pouvez acc&eacute;der et contr&ocirc;ler vos informations via notre centre de confidentialit&eacute; int&eacute;gr&eacute; &agrave; l'application (disponible sous Param&egrave;tres&gt; Centre de confidentialit&eacute;) o&ugrave; vous pouvez utiliser des outils pour afficher, rectifier, t&eacute;l&eacute;charger, restreindre le traitement ou supprimer vos donn&eacute;es. Vous pouvez &eacute;galement contacter transfusio pour obtenir de l'aide en utilisant les informations de contact ci-dessous, et nous examinerons votre demande conform&eacute;ment &agrave; la loi applicable.</span></p>
<h2><strong>CONFIDENTIALIT&Eacute; DES ENFANTS</strong></h2>
<p><span style="font-weight: 400;">Nous ne collectons ni ne sollicitons intentionnellement ou sciemment des informations aupr&egrave;s d'enfants n'ayant pas atteint l'&acirc;ge de consentement requis en vertu des lois de leurs juridictions respectives, ni n'autorisons sciemment ces personnes &agrave; s'inscrire aux Services. Les Services ne sont pas destin&eacute;s aux enfants et sont uniquement destin&eacute;s &agrave; &ecirc;tre utilis&eacute;s par des personnes ayant atteint l'&acirc;ge de consentement requis en vertu des lois de leurs juridictions respectives.</span></p>
<p><span style="font-weight: 400;">Si vous pensez que nous pourrions d&eacute;tenir des informations provenant de ou sur un enfant n'ayant pas atteint l'&acirc;ge de consentement requis, veuillez nous contacter &agrave; dpo.togo@migbloin.tg . Nous examinerons rapidement les informations et prendrons les mesures appropri&eacute;es, conform&eacute;ment &agrave; la loi applicable.</span></p>
<h2><strong>MODIFICATIONS APPORT&Eacute;ES &Agrave; CETTE POLITIQUE DE CONFIDENTIALIT&Eacute;</strong></h2>
<p><span style="font-weight: 400;">transfusio peut &agrave; tout moment modifier cette politique de confidentialit&eacute;. transfusio informera les utilisateurs de ces modifications par notification push ou via une notification dans les Services ou par d'autres moyens. Si vous vous opposez &agrave; toute modification, vous pouvez d&eacute;sactiver votre compte et cesser d'utiliser les Services. Votre utilisation continue des services apr&egrave;s que transfusio a communiqu&eacute; les modifications apport&eacute;es &agrave; cette politique de confidentialit&eacute; signifie que la collecte, l'utilisation, le partage et le traitement de vos informations personnelles sont soumis &agrave; la nouvelle politique de confidentialit&eacute;. Nous pouvons de temps &agrave; autre fournir des informations plus d&eacute;taill&eacute;es sur la mani&egrave;re dont nous traitons vos informations personnelles en relation avec des services particuliers dans des avis de confidentialit&eacute; suppl&eacute;mentaires qui seront incorpor&eacute;s et feront partie de la pr&eacute;sente politique de confidentialit&eacute;.</span></p>
<h2><strong>COOKIES</strong></h2>
<p><span style="font-weight: 400;">Comme d&eacute;crit dans notre&nbsp; Politique en mati&egrave;re de cookies , nous utilisons des cookies, des balises Web, des cookies flash, des cookies HTML 5, des balises pixel et d'autres m&eacute;thodes logicielles d'application Web, y compris des identifiants d'application mobile, pour nous aider &agrave; vous reconna&icirc;tre &agrave; travers les Services, &agrave; conna&icirc;tre vos int&eacute;r&ecirc;ts &agrave; la fois sur et en dehors des Services, am&eacute;liorer votre exp&eacute;rience, augmenter la s&eacute;curit&eacute;, mesurer l'utilisation et l'efficacit&eacute; des Services et diffuser de la publicit&eacute;. Vous pouvez contr&ocirc;ler les cookies via les param&egrave;tres de votre navigateur et d'autres outils. En interagissant avec les Services, vous consentez &agrave; l'utilisation et au placement de cookies sur votre appareil conform&eacute;ment &agrave; notre Politique de confidentialit&eacute;, qui int&egrave;gre par r&eacute;f&eacute;rence notre&nbsp; Politique en mati&egrave;re de cookies .</span></p>
<h2><strong>CONTACTEZ-NOUS</strong></h2>
<p><span style="font-weight: 400;">Pour toute demande g&eacute;n&eacute;rale concernant notre politique de confidentialit&eacute;, n'h&eacute;sitez pas &agrave; nous contacter &agrave; support@migbloin.tg.</span></p>
<p><span style="font-weight: 400;">Nous respectons votre vie priv&eacute;e et visons &agrave; traiter et rem&eacute;dier &agrave; votre grief au mieux de nos capacit&eacute;s. Si vous avez des questions sp&eacute;cifiques sur notre politique de confidentialit&eacute;, y compris sur la collecte, l'utilisation ou le partage de vos informations ou l'acc&egrave;s &agrave; vos informations, veuillez contacter notre d&eacute;l&eacute;gu&eacute; &agrave; la protection des donn&eacute;es &agrave; dpo.togo@migbloin.tg ou par courrier &agrave; &laquo; le d&eacute;l&eacute;gu&eacute; &agrave; la protection des donn&eacute;es &raquo;. - Togo &agrave; l'adresse ci-dessous. Nous nous effor&ccedil;ons de r&eacute;soudre votre r&eacute;clamation dans un d&eacute;lai de 30 jours &agrave; compter de sa r&eacute;ception.</span></p>
<p><span style="font-weight: 400;">Si vous avez des griefs, veuillez contacter le responsable des plaintes &agrave; plaintes@migbloin.tg ou par courrier &agrave; &laquo; le responsable des plaintes &raquo; &agrave; l'adresse ci-dessous.</span></p>
<p><span style="font-weight: 400;">transfusio</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">Ago&egrave; Minamadou</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">pr&egrave;s de l&rsquo;Ecole Sup&eacute;rieur des Affaires,</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">Tel : 228 90 00 18 86</span></p>
<p><span style="font-weight: 400;">Email : nsaatechtg@gmail.com</span></p>
<h2><strong>RECOURS DISPONIBLES</strong></h2>
<p><span style="font-weight: 400;">Le recours que nous appliquons pour traiter votre r&eacute;clamation d&eacute;pend de la nature de la r&eacute;clamation mais peut inclure : (a) la conduite d'une enqu&ecirc;te seul (ou en collaboration avec un organisme de conformit&eacute; en mati&egrave;re de protection des donn&eacute;es) pour &eacute;tablir et traiter la source de votre r&eacute;clamation, ( b) suppression de vos donn&eacute;es de notre base de donn&eacute;es, (c) rectification de vos donn&eacute;es, ou (d) imposition de restrictions sur le traitement ult&eacute;rieur de vos donn&eacute;es, etc.</span></p>
<p><span style="font-weight: 400;">Date d'entr&eacute;e en vigueur : 29 d&eacute;cembre 2023</span></p>
<h1><br /><br /></h1>""",
                    ),
          ),
        ],
      ),
    );
  }
}
