// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFIwwtTn5qTSZ1P_mxH7YR1foFj9Qp15o',
    appId: '1:479625373940:web:3a28d934535323b39796a1',
    messagingSenderId: '479625373940',
    projectId: 'transfusio-2707d',
    authDomain: 'transfusio-2707d.firebaseapp.com',
    storageBucket: 'transfusio-2707d.firebasestorage.app',
    measurementId: 'G-PLJ3F81JC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK0xNW3GYQKWT69iaCtRdz-UGVHvoiHfs',
    appId: '1:479625373940:android:b55d92edbbead3969796a1',
    messagingSenderId: '479625373940',
    projectId: 'transfusio-2707d',
    storageBucket: 'transfusio-2707d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlC7HcTvsoMKFLO1Ow19LfY4B_bPUzJQ4',
    appId: '1:479625373940:ios:9d3eb7d9c83aa2ff9796a1',
    messagingSenderId: '479625373940',
    projectId: 'transfusio-2707d',
    storageBucket: 'transfusio-2707d.firebasestorage.app',
    iosBundleId: 'com.transfusio.www',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlC7HcTvsoMKFLO1Ow19LfY4B_bPUzJQ4',
    appId: '1:479625373940:ios:9d3eb7d9c83aa2ff9796a1',
    messagingSenderId: '479625373940',
    projectId: 'transfusio-2707d',
    storageBucket: 'transfusio-2707d.firebasestorage.app',
    iosBundleId: 'com.transfusio.www',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFIwwtTn5qTSZ1P_mxH7YR1foFj9Qp15o',
    appId: '1:479625373940:web:dc8c3ba4b5b6b3c59796a1',
    messagingSenderId: '479625373940',
    projectId: 'transfusio-2707d',
    authDomain: 'transfusio-2707d.firebaseapp.com',
    storageBucket: 'transfusio-2707d.firebasestorage.app',
    measurementId: 'G-2ECMJM3RHN',
  );
}
